AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.3
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'

# Проверяет длину строки
Layout/LineLength:
  Max: 120

# Проверяет наличие утверждений raise или fail
Lint/RaiseException:
  Enabled: true

# Проверяет неожиданные переопределения Struct встроенных методов через Struct.new
Lint/StructNewOverride:
  Enabled: true

# Проверяет превышает ли длина блока какое-то максимальное значение
Metrics/BlockLength:
  Max: 35

# Проверяет превышает ли длина метода какое-то максимальное значение
Metrics/MethodLength:
  Max: 15

# Использование методов хеширования
Style/HashEachMethods:
  Enabled: true

# Для использования преобразования ключей хэша
Style/HashTransformKeys:
  Enabled: true

# Для использования преобразования значений хэша
Style/HashTransformValues:
  Enabled: true

# Наличие не английских комментариев
Style/AsciiComments:
  Enabled: false

# Отсутствие документации верхнего уровня по классам и модулям
Style/Documentation:
  Enabled: false

# Замороженные строковые литералы
Style/FrozenStringLiteralComment:
  Enabled: false
